14sprint.1 version: feat:bookings.
BegemotKotei/java-shareit pull request #2
Opened 2023-04-18 15:02 UTC by BegemotKotei

2023-04-18 18:38 UTC, andrew-larkin requested changes
Привет! Очень качественная реализация, чистый код. Остается внести пару небольших правок и работа будет принята.

2023-04-18 18:38 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +
@Repository над всеми репозиториями

2023-04-18 18:38 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
не стоит возвращать голый объект из БД - можем словить NPE. Лучше обернуть в класс Optional  и доставать сущность уже в сервисе с помощью метода .orElseThrow()

2023-04-18 18:38 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestBody @Valid ItemDto itemDto,
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.createItem(userId, itemDto));
Для всех методов во всех контроллерах стоит его добавить

2023-04-18 18:38 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/mapper/EntityMapper.java
> +public interface EntityMapper {
т.к. мапперов может быть несколько, лучше называть их в соответствии с классами, с которыми он работает

2023-04-19 08:20 UTC, BegemotKotei commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestBody @Valid ItemDto itemDto,
Хорошо

2023-04-19 09:17 UTC, BegemotKotei commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
Не могу догнать как это реализовать в ItemServiceImpl для метовов getItem() и getItemsByUser(). В repository оборачиваю, например, Optional<Booking> findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
            Long itemId, Long userId, LocalDateTime end, Sort sort);
А в ItemServiceImpl добавляю InfoBookingDto lastBooking = mapper.toInfoBookingDto(bookingRepository
                .findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
                        itemId,
                        userId,
                        SORT_DESC).orElseThrow());
Выпадает ошибка, как я понимаю из-за того, что я не достал из Optional объект? Если так, то как это можно исправит?
![2023-04-19_15-58-50](https://user-images.githubusercontent.com/104847507/233029165-18db99ef-708f-4edc-ba2c-1375dfbd750d.png)

2023-04-19 09:23 UTC, BegemotKotei commented on src/main/java/ru/practicum/shareit/mapper/EntityMapper.java
> +public interface EntityMapper {
Согласен, но не смог придумать название так как я его используется во всех ServiceImpl. Как быть в такой ситуации? Оставить как есть? Просто, если в дальнейшим больше мапперов не пригодится, может оставить?

2023-04-19 09:38 UTC, BegemotKotei commented
Привет! Спасибо, за ревью, вопросы задал, где не смог решить=)

2023-04-20 12:15 UTC, merged